env: dev
replica: 1
component: frontend
service:
  port: 80
  containerPort: 80

initContainers:
  parameters_pull:
    image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/parameter-store-init-container-image:1.0.0
    imagePullPolicy: Always

containers:
  main:
    image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/frontend:1.0.1
    imagePullPolicy: Always

ingress:
  enabled: true



