env: dev
replica: 1
PARAMS: "dev.roboshop.shipping.CART_ENDPOINT,CART_ENDPOINT dev.roboshop.shipping.DB_HOST,DB_HOST"

job:
  PARAMS: "dev.roboshop.rds.endpoint,DB_HOST dev.roboshop.rds.username,DB_USER dev.roboshop.rds.password,DB_PASS"
component: shipping
schema_type: mysql
service:
  port: 80
  containerPort: 8080

initContainers:
  parameters_pull:
    image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/parameter-store-init-container-image:1.0.0
    imagePullPolicy: Always

containers:
  main:
    image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/shipping:1.0.1
    imagePullPolicy: Always
  schema_loader:
    image: 739561048503.dkr.ecr.us-east-1.amazonaws.com/schema-loader:1.0.0
    imagePullPolicy: Always

